spring:
  datasource:
    driver-class-name:  com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/sp?useUnicode=true&characterEncoding=utf-8
server:
  port: 6897
  context-path: /api/

